In [1]:
import matplotlib
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from pandas import *
%matplotlib inline 

import warnings
warnings.filterwarnings('ignore')

cmap = sns.diverging_palette(220, 10, as_cmap=True)

In [4]:
def read_data(location):
    location = location[['id', 'room_type', 'price', 'minimum_nights', 'availability_365', 'number_of_reviews', 
                         'reviews_per_month', 'calculated_host_listings_count']]
    return location

def get_stats(location):
    x = ['price', 'minimum_nights', 'availability_365', 'number_of_reviews', 'reviews_per_month', 'calculated_host_listings_count']
    location = location.loc[:, x]
    location_stats = location.describe()
    location_stats = concat([location_stats.ix[0:4], location_stats.ix[7:]])
    return location_stats

def reorder(location):
    new = location.set_index('location', append = True).unstack(0)
    return new

# Airbnb Data Pre-Processing
## 1 - Reading & Cleaning
A look into the Airbnb listing features provided for each city by the data:

In [5]:
amsterdam = read_csv('Amsterdam-Data/listings.csv')
amsterdam = read_data(amsterdam)
amsterdam['price'] = amsterdam['price'].map(lambda x: str(x)[1:]).convert_objects(convert_numeric=True)

athens = read_csv('Athens-Data/listings.csv')
athens = read_data(athens)
athens['price'] = athens['price'].map(lambda x: str(x)[1:]).convert_objects(convert_numeric=True)

barcelona = read_csv('Barcelona-Data/listings.csv')
barcelona = read_data(barcelona)
barcelona['price'] = barcelona['price'].map(lambda x: str(x)[1:]).convert_objects(convert_numeric=True)

berlin = read_csv('Berlin-Data/listings.csv')
berlin = read_data(berlin)
berlin['price'] = berlin['price'].map(lambda x: str(x)[1:]).convert_objects(convert_numeric=True)

brussels = read_csv('Brussels-Data/listings.csv')
brussels = read_data(brussels)
brussels['price'] = brussels['price'].map(lambda x: str(x)[1:]).convert_objects(convert_numeric=True)

copenhagen = read_csv('Copenhagen-Data/listings.csv')
copenhagen = read_data(copenhagen)
copenhagen['price'] = copenhagen['price'].map(lambda x: str(x)[1:]).convert_objects(convert_numeric=True)

dublin = read_csv('Dublin-Data/listings.csv')
dublin = read_data(dublin)
dublin['price'] = dublin['price'].map(lambda x: str(x)[1:]).convert_objects(convert_numeric=True)

edinburgh = read_csv('Edinburgh-Data/listings.csv')
edinburgh = read_data(edinburgh)
edinburgh['price'] = edinburgh['price'].map(lambda x: str(x)[1:]).convert_objects(convert_numeric=True)

florence = read_csv('Florence-Data/listings.csv')
florence = read_data(florence)
florence['price'] = florence['price'].map(lambda x: str(x)[1:]).convert_objects(convert_numeric=True)

geneva = read_csv('Geneva-Data/listings.csv')
geneva = read_data(geneva)
geneva['price'] = geneva['price'].map(lambda x: str(x)[1:]).convert_objects(convert_numeric=True)

istanbul = read_csv('Istanbul-Data/listings.csv')
istanbul = read_data(istanbul)
istanbul['price'] = istanbul['price'].map(lambda x: str(x)[1:]).convert_objects(convert_numeric=True)

lisbon = read_csv('Lisbon-Data/listings.csv')
lisbon = read_data(lisbon)
lisbon['price'] = lisbon['price'].map(lambda x: str(x)[1:]).convert_objects(convert_numeric=True)

london = read_csv('London-Data/listings.csv')
london = read_data(london)
london['price'] = london['price'].map(lambda x: str(x)[1:]).convert_objects(convert_numeric=True)

lyon = read_csv('Lyon-Data/listings.csv')
lyon = read_data(lyon)
lyon['price'] = lyon['price'].map(lambda x: str(x)[1:]).convert_objects(convert_numeric=True)

madrid = read_csv('Madrid-Data/listings.csv')
madrid = read_data(madrid)
madrid['price'] = madrid['price'].map(lambda x: str(x)[1:]).convert_objects(convert_numeric=True)

manchester = read_csv('Manchester-Data/listings.csv')
manchester = read_data(manchester)
manchester['price'] = manchester['price'].map(lambda x: str(x)[1:]).convert_objects(convert_numeric=True)

milan = read_csv('Milan-Data/listings.csv')
milan = read_data(milan)
milan['price'] = milan['price'].map(lambda x: str(x)[1:]).convert_objects(convert_numeric=True)

oslo = read_csv('Oslo-Data/listings.csv')
oslo = read_data(oslo)
oslo['price'] = oslo['price'].map(lambda x: str(x)[1:]).convert_objects(convert_numeric=True)

paris = read_csv('Paris-Data/listings.csv')
paris = read_data(paris)
paris['price'] = paris['price'].map(lambda x: str(x)[1:]).convert_objects(convert_numeric=True)

prague = read_csv('Prague-Data/listings.csv')
prague = read_data(prague)
prague['price'] = prague['price'].map(lambda x: str(x)[1:]).convert_objects(convert_numeric=True)

rome = read_csv('Rome-Data/listings.csv')
rome = read_data(rome)
rome['price'] = rome['price'].map(lambda x: str(x)[1:]).convert_objects(convert_numeric=True)

stockholm = read_csv('Stockholm-Data/listings.csv')
stockholm = read_data(stockholm)
stockholm['price'] = stockholm['price'].map(lambda x: str(x)[1:]).convert_objects(convert_numeric=True)

venice = read_csv('Venice-Data/listings.csv')
venice = read_data(venice)
venice['price'] = venice['price'].map(lambda x: str(x)[1:]).convert_objects(convert_numeric=True)

vienna = read_csv('Vienna-Data/listings.csv')
vienna = read_data(vienna)
vienna['price'] = vienna['price'].map(lambda x: str(x)[1:]).convert_objects(convert_numeric=True)

## 2 - Getting Statistics on Airbnb Data:
Creating a dataframe to house statistical summaries of the listing data so that we can analyze listing trends.

In [6]:
amsterdam_s = get_stats(amsterdam)
amsterdam_s['location'] = 'Amsterdam, NED'
amsterdam_s = reorder(amsterdam_s)

athens_s = get_stats(athens)
athens_s['location'] = 'Athens, GRE'
athens_s = reorder(athens_s)

barcelona_s = get_stats(barcelona)
barcelona_s['location'] = 'Barcelona, ESP'
barcelona_s = reorder(barcelona_s)

berlin_s = get_stats(berlin)
berlin_s['location'] = 'Berlin, GER'
berlin_s = reorder(berlin_s)

brussels_s = get_stats(brussels)
brussels_s['location'] = 'Brussels, BEL'
brussels_s = reorder(brussels_s)

copenhagen_s = get_stats(copenhagen)
copenhagen_s['location'] = 'Copenhagen, DEN'
copenhagen_s = reorder(copenhagen_s)

dublin_s = get_stats(dublin)
dublin_s['location'] = 'Dublin, IRE'
dublin_s = reorder(dublin_s)

edinburgh_s = get_stats(edinburgh)
edinburgh_s['location'] = 'Edinburgh, SCO'
edinburgh_s = reorder(edinburgh_s)

florence_s = get_stats(florence)
florence_s['location'] = 'Florence, ITA'
florence_s = reorder(florence_s)

geneva_s = get_stats(geneva)
geneva_s['location'] = 'Geneva, SWI'
geneva_s = reorder(geneva_s)

istanbul_s = get_stats(istanbul)
istanbul_s['location'] = 'Istanbul, TUR'
istanbul_s = reorder(istanbul_s)

lisbon_s = get_stats(lisbon)
lisbon_s['location'] = 'Lisbon, POR'
lisbon_s = reorder(lisbon_s)

london_s = get_stats(london)
london_s['location'] = 'London, ENG'
london_s = reorder(london_s)

lyon_s = get_stats(lyon)
lyon_s['location'] = 'Lyon, FRA'
lyon_s = reorder(lyon_s)

madrid_s = get_stats(madrid)
madrid_s['location'] = 'Madrid, ESP'
madrid_s = reorder(madrid_s)

manchester_s = get_stats(manchester)
manchester_s['location'] = 'Manchester, ENG'
manchester_s = reorder(manchester_s)

milan_s = get_stats(milan)
milan_s['location'] = 'Milan, ITA'
milan_s = reorder(milan_s)

oslo_s = get_stats(oslo)
oslo_s['location'] = 'Oslo, NOR'
oslo_s = reorder(oslo_s)

paris_s = get_stats(paris)
paris_s['location'] = 'Paris, FRA'
paris_s = reorder(paris_s)

prague_s = get_stats(prague)
prague_s['location'] = 'Prague, CZE'
prague_s = reorder(prague_s)

rome_s = get_stats(rome)
rome_s['location'] = 'Rome, ITA'
rome_s = reorder(rome_s)

stockholm_s = get_stats(stockholm)
stockholm_s['location'] = 'Stockholm, SWE'
stockholm_s = reorder(stockholm_s)

venice_s = get_stats(venice)
venice_s['location'] = 'Venice, ITA'
venice_s = reorder(venice_s)

vienna_s = get_stats(vienna)
vienna_s['location'] = 'Vienna, AUS'
vienna_s = reorder(vienna_s)

In [8]:
statistics = concat([amsterdam_s, athens_s, barcelona_s, berlin_s, brussels_s, copenhagen_s, dublin_s, edinburgh_s, 
                     florence_s, geneva_s, istanbul_s, lisbon_s, london_s, lyon_s, madrid_s, manchester_s,
                    milan_s, oslo_s, paris_s, prague_s, rome_s, stockholm_s, venice_s, vienna_s])
statistics

                   price                                       minimum_nights  \
                   count      max        mean  min         std          count
location
Amsterdam, NED   19534.0    600.0   27.517303  0.0   28.755842        19538.0
Athens, GRE       7801.0    999.0    7.034867  0.0   19.873609         7828.0
Barcelona, ESP   17754.0    980.0   12.488228  0.0   23.862030        17788.0
Berlin, GER      26294.0    900.0    6.588385  0.0   14.924848        26323.0
Brussels, BEL     7042.0    944.0    7.242545  0.0   18.598432         7049.0
Copenhagen, DEN  25460.0   7877.0   98.998154  0.0  168.443335        25465.0
Dublin, IRE       9023.0    690.0   15.863238  0.0   24.875414         9028.0
Edinburgh, SCO    9628.0    999.0   12.651849  0.0   31.325715         9638.0
Florence, ITA    10833.0    800.0   12.705160  0.0   24.937478        10842.0
Geneva, SWI       3103.0    900.0   18.604576  0.0   38.834444         3107.0
Istanbul, TUR    12650.0   9903.0   44.346008  0.0  153.816065        12658.0
Lisbon, POR      20416.0    650.0    9.470905  0.0   21.793144        20493.0
London, ENG      72131.0    999.0   15.919106  0.0   29.492531        72218.0
Lyon, FRA        11253.0    500.0   10.424776  0.0   19.417508        11258.0
Madrid, ESP      18353.0    890.0    8.862747  0.0   19.489942        18362.0
Manchester, ENG   3137.0   1900.0    9.267772  0.0   37.809046         3145.0
Milan, ITA       18192.0    700.0   11.824099  0.0   24.264395        18200.0
Oslo, NOR         7770.0   8601.0  126.104376  0.0  238.685511         7773.0
Paris, FRA       62816.0   5000.0   13.135364  0.0   54.687150        62848.0
Prague, CZE      13000.0  55352.0  340.914385  0.0  791.380916        13004.0
Rome, ITA        28499.0   1089.0   12.736096  0.0   29.537444        28518.0
Stockholm, SWE    7144.0   5004.0  167.194149  0.0  238.532427         7146.0
Venice, ITA       7732.0    900.0   21.907527  0.0   29.626500         7738.0
Vienna, AUS      10738.0    510.0    8.543397  0.0   17.743451        10744.0

                                                           ...      \
                      max       mean  min          std     ...
location                                                   ...
Amsterdam, NED     1001.0   3.077388  1.0    10.986325     ...
Athens, GRE         700.0   2.750128  1.0    17.388610     ...
Barcelona, ESP      365.0   3.277209  1.0     7.961353     ...
Berlin, GER        5000.0   4.817156  1.0    34.391410     ...
Brussels, BEL      1000.0   4.996595  1.0    21.812299     ...
Copenhagen, DEN    1000.0   3.266366  1.0    12.105597     ...
Dublin, IRE        1000.0   2.834515  1.0    13.582642     ...
Edinburgh, SCO     1000.0   3.064121  1.0    20.712068     ...
Florence, ITA       365.0   2.363771  1.0     6.148557     ...
Geneva, SWI       10000.0   7.028645  1.0   179.622182     ...
Istanbul, TUR      1000.0   3.008374  1.0    19.347516     ...
Lisbon, POR         800.0   2.650856  1.0     7.931198     ...
London, ENG         900.0   3.135645  1.0     7.930014     ...
Lyon, FRA            60.0   2.174365  1.0     2.784791     ...
Madrid, ESP         700.0   3.120085  1.0    11.486039     ...
Manchester, ENG     365.0   2.282035  1.0    10.547042     ...
Milan, ITA       500000.0  30.335440  1.0  3706.250427     ...
Oslo, NOR           500.0   3.094815  1.0     9.020942     ...
Paris, FRA        10000.0   4.964661  1.0    61.937587     ...
Prague, CZE       50000.0   6.397109  1.0   438.659490     ...
Rome, ITA          1000.0   2.402974  1.0    11.953439     ...
Stockholm, SWE      500.0   4.119228  1.0    14.568563     ...
Venice, ITA          50.0   2.178341  1.0     1.602227     ...
Vienna, AUS        1000.0   3.498883  1.0    16.440268     ...

                reviews_per_month                                    \
                            count     max      mean   min       std
location
Amsterdam, NED            17108.0   72.46  1.111769  0.01  1.600833
Athens, GRE                5947.0  138.18  2.249939  0.01  3.028790
Barcelona, ESP            14748.0   65.84  1.798457  0.01  1.692814
Berlin, GER               21490.0   31.34  1.061641  0.01  1.375658
Brussels, BEL              5787.0  389.00  1.805073  0.01  6.072850
Copenhagen, DEN           20827.0   23.16  0.752716  0.01  0.967519
Dublin, IRE                7532.0   73.27  2.059344  0.01  2.200524
Edinburgh, SCO             8560.0   18.00  2.498798  0.01  2.352915
Florence, ITA              9123.0   28.20  2.088293  0.01  2.011556
Geneva, SWI                2452.0   21.11  1.297863  0.02  1.730443
Istanbul, TUR              5114.0    8.00  0.719628  0.01  0.921896
Lisbon, POR               16886.0   52.89  1.699552  0.01  1.637661
London, ENG               52556.0   65.13  1.223483  0.01  1.428023
Lyon, FRA                  8362.0   27.00  1.133949  0.01  1.596163
Madrid, ESP               14764.0   20.21  2.055453  0.01  2.000405
Manchester, ENG            2535.0   78.99  2.141531  0.02  2.865777
Milan, ITA                14321.0   16.48  1.416206  0.01  1.885888
Oslo, NOR                  5521.0   32.96  1.103874  0.02  1.613052
Paris, FRA                48865.0  224.00  1.183673  0.01  1.736284
Prague, CZE               10948.0   32.87  1.960406  0.01  1.939013
Rome, ITA                 22232.0   57.16  1.665405  0.01  1.751272
Stockholm, SWE             5443.0   34.17  0.892453  0.02  1.339138
Venice, ITA                6700.0   49.86  2.271487  0.01  2.230442
Vienna, AUS                8630.0   15.46  1.681220  0.01  1.868614

                calculated_host_listings_count                         \
                                         count    max       mean  min
location
Amsterdam, NED                         19538.0  108.0   3.577336  1.0
Athens, GRE                             7828.0   77.0   6.458866  1.0
Barcelona, ESP                         17788.0  148.0   9.685518  1.0
Berlin, GER                            26323.0   43.0   1.781142  1.0
Brussels, BEL                           7049.0   68.0   4.817563  1.0
Copenhagen, DEN                        25465.0   45.0   1.300255  1.0
Dublin, IRE                             9028.0   40.0   2.906513  1.0
Edinburgh, SCO                          9638.0   80.0   3.142146  1.0
Florence, ITA                          10842.0  167.0  13.541229  1.0
Geneva, SWI                             3107.0   76.0   4.448986  1.0
Istanbul, TUR                          12658.0   79.0   4.117712  1.0
Lisbon, POR                            20493.0  259.0  12.254965  1.0
London, ENG                            72218.0  995.0  20.974937  1.0
Lyon, FRA                              11258.0   78.0   2.180139  1.0
Madrid, ESP                            18362.0  205.0  12.016992  1.0
Manchester, ENG                         3145.0   24.0   3.434976  1.0
Milan, ITA                             18200.0  166.0   6.053297  1.0
Oslo, NOR                               7773.0  219.0   8.405120  1.0
Paris, FRA                             62848.0  134.0   3.804512  1.0
Prague, CZE                            13004.0  131.0  10.540757  1.0
Rome, ITA                              28518.0  132.0   6.162845  1.0
Stockholm, SWE                          7146.0   33.0   1.457879  1.0
Venice, ITA                             7738.0  132.0  11.768157  1.0
Vienna, AUS                            10744.0   93.0   5.600521  1.0


                        std
location
Amsterdam, NED    13.082243
Athens, GRE       13.683493
Barcelona, ESP    22.324260
Berlin, GER        3.409751
Brussels, BEL     11.588365
Copenhagen, DEN    2.052257
Dublin, IRE        4.622148
Edinburgh, SCO     8.147756
Florence, ITA     30.970911
Geneva, SWI       12.193475
Istanbul, TUR      8.593920
Lisbon, POR       32.859845
London, ENG      117.049914
Lyon, FRA          6.893076
Madrid, ESP       31.399732
Manchester, ENG    4.391067
Milan, ITA        18.667326
Oslo, NOR         36.799815
Paris, FRA        12.721669
Prague, CZE       20.428358
Rome, ITA         14.047362
Stockholm, SWE     2.568415
Venice, ITA       24.153499
Vienna, AUS       13.253314

[24 rows x 30 columns]

Columns included in statistical summary:

In [9]:
statistics.columns.values

array([('price', 'count'), ('price', 'max'), ('price', 'mean'),
       ('price', 'min'), ('price', 'std'), ('minimum_nights', 'count'),
       ('minimum_nights', 'max'), ('minimum_nights', 'mean'),
       ('minimum_nights', 'min'), ('minimum_nights', 'std'),
       ('availability_365', 'count'), ('availability_365', 'max'),
       ('availability_365', 'mean'), ('availability_365', 'min'),
       ('availability_365', 'std'), ('number_of_reviews', 'count'),
       ('number_of_reviews', 'max'), ('number_of_reviews', 'mean'),
       ('number_of_reviews', 'min'), ('number_of_reviews', 'std'),
       ('reviews_per_month', 'count'), ('reviews_per_month', 'max'),
       ('reviews_per_month', 'mean'), ('reviews_per_month', 'min'),
       ('reviews_per_month', 'std'),
       ('calculated_host_listings_count', 'count'),
       ('calculated_host_listings_count', 'max'),
       ('calculated_host_listings_count', 'mean'),
       ('calculated_host_listings_count', 'min'),
       ('calculated_host_listings_count', 'std')], dtype=object)